### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by crutchcorn** [JL102/pack-mmip#1]
Please publish this package to NPM. This would be a great help for easily packaging tools

I could have `pack-mmip` deployed to my machine using `npm i -g pack-mmip` or even install it as a project dependency `npm i pack-mmip` and use in a `build` script

**Comment by pepper-lees** [comment]
Good idea. I'm not exactly sure why I didn't go the NPM route in the first place - Maybe it's because I didn't know `process.pwd()` was a thing, and thought I needed to use my own custom batch files. In any case: it's done! https://www.npmjs.com/package/pack-mmip

**Comment by crutchcorn** [comment]
Haha no worries - I've done the same myself a million times. Huge thank you! 🎉
